/**
 * ESLint flat config (ESLint 9/10).
 *
 * Complements the existing gates: `typecheck` (@ts-check on the hot modules)
 * checks types, `test:unit` checks behaviour, this checks static style/bugs
 * (unused vars, loose equality, dead code, undeclared globals…).
 *
 * Environment split:
 *  - js/**       → browser globals (window, document, localStorage…) plus the
 *                  few script-tag globals the app reads (bootstrap, Diff).
 *  - public/sw.js→ worker globals (self, caches, importScripts…).
 *  - scripts/**, server.js, tests/** → Node/Bun globals.
 *  - js/app.js   → ignored: committed build artifact (regenerated by build).
 */
import js from '@eslint/js';
import globals from 'globals';

const SHARED_RULES = {
  'eqeqeq': ['error', 'smart'],
  // The codebase deliberately uses best-effort `catch (_) {}` silencers.
  'no-empty': ['error', { allowEmptyCatch: true }],
  'no-unused-vars': ['error', {
    argsIgnorePattern: '^_',
    varsIgnorePattern: '^_',
    // The codebase deliberately silences errors with `catch (_) {}`.
    caughtErrors: 'all',
    caughtErrorsIgnorePattern: '^_',
  }],
  'no-constant-condition': ['error', { checkLoops: false }],
  // ─── Hardened quality rules (see docs/DEVELOPMENT.md for the rationale) ───
  'prefer-const': 'error',
  'no-var': 'error',
  'no-eval': 'error',
  'no-implied-eval': 'error',
  'no-promise-executor-return': 'error',
  'no-unreachable-loop': 'error',
  'radix': 'error',
  // Legacy-aware caps: the codebase predates these limits, so the thresholds
  // sit just above today's worst offenders (see DEVELOPMENT.md).
  'complexity': ['error', 30],
  'max-depth': ['error', 5],
  'no-shadow': 'error',
};

// Debug noise: stray console.log/info/debug are only a problem in the browser
// runtime — the CLI scripts (scripts/**, server.js) legitimately print to stdout.
const BROWSER_RULES = {
  ...SHARED_RULES,
  'no-console': ['error', { allow: ['error', 'warn'] }],
};

export default [
  {
    ignores: [
      'js/app.js', // build artifact (bun scripts/build.mjs)
      'node_modules/**',
      'playwright-report/**',
      'test-results/**',
      'bun.lock',
    ],
  },

  // Recommended JS rules (applied first, then the environment blocks below).
  js.configs.recommended,

  // Browser modules — the app's runtime code.
  {
    files: ['js/**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        bootstrap: 'readonly', // loaded via <script> tag (bootstrap bundle)
        Diff: 'readonly',      // loaded via <script> tag (jsdiff)
        // CDN script-tag globals (lazy-loaded, guarded with typeof checks).
        anime: 'readonly',
        marked: 'readonly',
        DOMPurify: 'readonly',
      },
    },
    rules: BROWSER_RULES,
  },

  // Service worker — worker globals instead of window/document.
  {
    files: ['public/sw.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.worker,
        importScripts: 'readonly',
      },
    },
    rules: BROWSER_RULES,
  },

  // Node/Bun tooling: server, release scripts, unit + e2e tests.
  // Tests also stub browser globals (window/document/localStorage), so they
  // get the browser set too. CardStorage/CardEngine are page-context globals
  // used inside page.evaluate() blocks of the e2e specs.
  {
    files: ['server.js', 'playwright.config.js', 'scripts/**/*.mjs', 'tests/**/*.js', 'tests/**/*.mjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.node,
        ...globals.browser,
        Bun: 'readonly', // Bun.serve / Bun.write used by server + scripts
        CardStorage: 'readonly',
        CardEngine: 'readonly',
      },
    },
    rules: SHARED_RULES,
  },
];