/**
 * vendor.mjs — download the pinned third-party assets into public/vendor/.
 *
 * Why vendor at all: every one of these files is remote code (or a stylesheet
 * that loads remote fonts) executed by the app. Loading them from a CDN means
 * the editor's integrity depends on a third party staying up, serving the same
 * bytes, and never being compromised — and the offline PWA only worked because
 * the service worker happened to have cached the CDN responses at runtime
 * (which is why a purge left the app styling-less, v2 #26).
 *
 * Vendored, they are: same-origin (so the CSP no longer allowlists
 * cdn.jsdelivr.net / cdnjs.cloudflare.com / esm.sh for scripts, nor
 * fonts.googleapis.com / fonts.gstatic.com for styles and fonts), committed (so
 * `check-assets` can verify what ships), and available offline from the shell
 * cache without any runtime CDN round-trip.
 *
 * Versions are pinned exactly, and a re-download whose bytes differ from the
 * hash already recorded in the manifest is REFUSED (the file is left untouched
 * and the run exits non-zero), so an upstream republish — or a hijacked CDN
 * response — cannot silently ship new code. `--force` is the deliberate
 * override for the one legitimate case: bumping a version below.
 *
 * Usage:
 *   bun scripts/vendor.mjs           # download/refresh public/vendor/*
 *   bun scripts/vendor.mjs --check   # verify local bytes against MANIFEST.txt
 *   bun scripts/vendor.mjs --force   # accept a changed hash (version bump)
 *
 * Re-run it only when intentionally bumping a dependency version below.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const vendorDir = join(root, "public", "vendor");
const manifestPath = join(vendorDir, "MANIFEST.txt");

// Google Fonts is the one asset whose upstream is a *generator* rather than a
// file: the CSS API answers with one @font-face per (family, weight, unicode
// subset), each pointing at a versioned woff2 on fonts.gstatic.com. Vendoring
// it therefore means pinning both halves — fetch the stylesheet once, download
// every woff2 it names, and rewrite the `src` URLs to those local copies. The
// committed fonts.css is a build product of that one fetch; re-running this
// script is what would notice the upstream changing.
const FONT_CSS = {
  out: "fonts.css",
  dir: "fonts",
  url: "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=Inter:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap",
  // Without a browser User-Agent the API serves legacy TTF, one file per
  // weight, instead of the woff2 variable fonts. Pinned so an upstream change
  // in UA sniffing shows up as manifest drift instead of silently swapping the
  // stylesheet's format.
  ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  header: (url) => `/* Google Fonts — generated by scripts/vendor.mjs, do not edit.\n`
    + `   Source: ${url}\n`
    + `   The @font-face rules and their unicode-range subsets are Google's; the\n`
    + `   src URLs were rewritten to the woff2 files vendored in ./${FONT_CSS.dir}/,\n`
    + `   which are committed and hash-checked against public/vendor/MANIFEST.txt. */\n`,
};

// Pinned sources. `out` is relative to public/vendor/ (kept in sync with the
// paths referenced by public/index.html, js/ui.js and js/tokenizer.js).
const ASSETS = [
  { out: "bootstrap.min.css", url: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" },
  { out: "bootstrap.rtl.min.css", url: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.rtl.min.css" },
  { out: "bootstrap.bundle.min.js", url: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" },
  // bootstrap-icons.css references ./fonts/bootstrap-icons.woff2 in the same
  // npm package, so the CSS and its fonts must stay siblings under vendor/.
  { out: "bootstrap-icons.css", url: "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" },
  { out: "fonts/bootstrap-icons.woff2", url: "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/fonts/bootstrap-icons.woff2" },
  { out: "fonts/bootstrap-icons.woff", url: "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/fonts/bootstrap-icons.woff" },
  { out: "diff.min.js", url: "https://cdn.jsdelivr.net/npm/diff@9.0.0/dist/diff.min.js" },
  { out: "anime.min.js", url: "https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.2/anime.min.js" },
  // marked/DOMPurify were loaded from *unpinned* jsdelivr URLs (…/npm/marked/…),
  // i.e. whatever the CDN resolved that day — pinning is part of the fix.
  { out: "marked.min.js", url: "https://cdn.jsdelivr.net/npm/marked@15.0.7/marked.min.js" },
  { out: "purify.min.js", url: "https://cdn.jsdelivr.net/npm/dompurify@3.2.6/dist/purify.min.js" },
  // gpt-tokenizer is ~2.8 MB, so it stays a lazy fetch (see js/tokenizer.js):
  // it is deliberately NOT precached with the app shell, and the service worker
  // caches it at runtime on first use instead.
  { out: "gpt-tokenizer.js", url: "https://esm.sh/gpt-tokenizer@3.0.1/es2022/gpt-tokenizer.mjs", lazy: true },
];

const sha384 = (bytes) => "sha384-" + createHash("sha384").update(bytes).digest("base64");

const slug = (label) => label.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");

/**
 * Turn Google's stylesheet into the list of files it needs, plus the rewritten
 * stylesheet itself.
 *
 * File naming: a face's family + unicode subset is enough to identify its
 * woff2, because Google serves these families as *variable* fonts — every
 * weight in a subset shares one file. Naming them `inter-latin.woff2` instead
 * of after the opaque gstatic basename keeps the service-worker shell and the
 * committed tree readable, and means a font version bump (same name, new
 * bytes) is caught by the manifest instead of churning every path that lists
 * the file. If a family ever stops being variable, the weight is appended to
 * disambiguate rather than letting two different files claim one name.
 *
 * @param {string} css
 * @returns {{ css: string, assets: { out: string, url: string }[] }}
 */
function buildFontAssets(css) {
  /** @type {{ family: string, subset: string, weight: string, url: string }[]} */
  const faces = [];
  const faceRe = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*{([^}]*)}/g;
  let m;
  while ((m = faceRe.exec(css))) {
    const [, subset, body] = m;
    const family = /font-family:\s*'([^']+)'/.exec(body)?.[1];
    const url = /url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/.exec(body)?.[1];
    if (!family || !url) continue;
    const weight = /font-weight:\s*(\d+)/.exec(body)?.[1] || "400";
    faces.push({ family: slug(family), subset, weight, url });
  }
  if (!faces.length) {
    throw new Error("the Google Fonts stylesheet referenced no fonts.gstatic.com woff2 — "
      + "the API response format changed, so the vendoring recipe needs updating.");
  }

  /** @type {Map<string, Set<string>>} family+subset -> distinct files */
  const files = new Map();
  for (const face of faces) {
    const key = `${face.family}-${face.subset}`;
    if (!files.has(key)) files.set(key, new Set());
    files.get(key).add(face.url);
  }

  /** @type {Map<string, string>} url -> local path (relative to public/) */
  const urlToOut = new Map();
  const assets = [];
  for (const face of faces) {
    const key = `${face.family}-${face.subset}`;
    const shared = files.get(key).size === 1;
    const out = `${FONT_CSS.dir}/${shared ? key : `${key}-${face.weight}`}.woff2`;
    if (urlToOut.has(face.url)) continue;
    urlToOut.set(face.url, out);
    assets.push({ out, url: face.url });
  }
  assets.sort((a, b) => a.out.localeCompare(b.out));

  const rewritten = css.replace(/https:\/\/fonts\.gstatic\.com\/[^)]+/g,
    (url) => urlToOut.get(url) || url);
  return { css: FONT_CSS.header(FONT_CSS.url) + rewritten, assets };
}

function readManifest() {
  /** @type {Map<string, { url: string, integrity: string, size: number }>} */
  const map = new Map();
  if (!existsSync(manifestPath)) return map;
  for (const line of readFileSync(manifestPath, "utf8").split("\n")) {
    // Format: "  <out> sha384-… <size> <url>". Entry lines are the only ones
    // indented by two spaces; comments start with `#`.
    if (!line.startsWith("  ")) continue;
    const parts = line.trim().split(/\s+/);
    const out = parts[0];
    // The integrity prefix is the real discriminator — keying on `=` dropped
    // every entry whose base64 hash happens to have no padding, which made
    // --check report a valid manifest as missing.
    if (!out || parts.length < 4 || !String(parts[1] || "").startsWith("sha384-")) continue;
    map.set(out, { integrity: parts[1] || "", size: Number(parts[2] || 0), url: parts[3] || "" });
  }
  return map;
}

async function check() {
  const manifest = readManifest();
  if (manifest.size === 0) {
    console.error("vendor --check: public/vendor/MANIFEST.txt is missing — run `bun scripts/vendor.mjs` first.");
    process.exit(1);
  }
  let bad = 0;
  for (const [out, expected] of manifest) {
    const file = join(vendorDir, out);
    if (!existsSync(file)) {
      console.error(`✗ vendor/${out} is missing`);
      bad++;
      continue;
    }
    const actual = sha384(readFileSync(file));
    if (actual !== expected.integrity) {
      console.error(`✗ vendor/${out} does not match the manifest (${actual} != ${expected.integrity})`);
      bad++;
    }
  }
  if (bad) {
    console.error(`vendor --check: ${bad} problem(s).`);
    process.exit(1);
  }
  console.log(`✓ ${manifest.size} vendored asset(s) match public/vendor/MANIFEST.txt.`);
}

/** @param {string} url @param {string} [ua] */
async function fetchBytes(url, ua) {
  const res = await fetch(url, ua ? { headers: { "User-Agent": ua } } : undefined);
  if (!res.ok) throw new Error(`${url} → HTTP ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

async function download() {
  const force = process.argv.includes("--force");
  const previous = readManifest();
  /** @type {string[]} */
  const lines = [];
  let bad = 0;

  /**
   * Write one asset unless its bytes drifted from the manifest, in which case
   * refuse (the whole point of the manifest is that shipped bytes are the
   * reviewed ones) and let the operator re-run with --force.
   *
   * @param {{ out: string, url: string }} asset
   * @param {Buffer} bytes
   */
  const store = (asset, bytes) => {
    const integrity = sha384(bytes);
    const known = previous.get(asset.out);
    const drift = known && known.integrity !== integrity;
    if (drift && !force) {
      console.error(`✗ ${asset.url} returned different bytes than the manifest records`
        + `\n    recorded ${known.integrity}`
        + `\n    fetched  ${integrity}`
        + `\n  vendor/${asset.out} left untouched. Re-run with --force only if you are bumping the version.`);
      lines.push(`  ${asset.out} ${known.integrity} ${known.size} ${known.url}`);
      bad++;
      return bytes;
    }
    const target = join(vendorDir, asset.out);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, bytes);
    lines.push(`  ${asset.out} ${integrity} ${bytes.byteLength} ${asset.url}`);
    const size = `${(bytes.byteLength / 1024).toFixed(1)} KB`;
    console.log(`${drift ? "↻" : "↳"} vendor/${asset.out} (${size})${drift ? "  ← differs from the previous download" : ""}`);
    return bytes;
  };

  // 1. Google Fonts: the stylesheet is generated from the upstream response, so
  //    it is written last — after we know which fonts it can point at.
  const upstreamCss = await fetchBytes(FONT_CSS.url, FONT_CSS.ua).then((b) => b.toString("utf8"));
  const fonts = buildFontAssets(upstreamCss);
  for (const font of fonts.assets) store(font, await fetchBytes(font.url));
  // The stylesheet goes last: it is only complete once we know which files it
  // may point at. Its own bytes are hash-checked like any other asset, so an
  // upstream change to the API response has to be accepted with --force.
  store({ out: FONT_CSS.out, url: FONT_CSS.url }, Buffer.from(fonts.css, "utf8"));

  // 2. Everything else, straight from its pinned URL.
  for (const asset of ASSETS) {
    const bytes = await fetchBytes(asset.url).catch((err) => {
      console.error(`✗ ${err.message}`);
      bad++;
      return null;
    });
    if (!bytes) continue;
    store(asset, bytes);
  }

  writeFileSync(manifestPath, manifestHeader().concat(lines).join("\n") + "\n", "utf8");
  console.log(`✓ wrote ${lines.length} asset(s) + public/vendor/MANIFEST.txt`);
  if (bad) process.exitCode = 1;
}

function manifestHeader() {
  return [
    "# Vendored third-party assets — see scripts/vendor.mjs.",
    "#",
    "# These files are committed on purpose: they are remote code the app used to",
    "# execute straight from a CDN. Re-running scripts/vendor.mjs verifies each",
    "# download against the hash below, so an upstream change fails loudly here",
    "# instead of shipping silently. Do not edit these files by hand.",
    "#",
    "# <file> <sha384> <bytes> <source>",
    "",
  ];
}

if (process.argv.includes("--check")) await check();
else await download();
